# Generated by Django 4.1.1 on 2022-09-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='data',
            new_name='date',
        ),
    ]
